version: "2"

services:
  django-site:
    build: .
    # with the following line, an alternativ python app could be started
    # command: python3 manage.py blabla
    ports:
      - "8000:800"
    volumes:
      - .:/code
#    restart: always
#network_mode: "host"