version: "2"

networks:
  macs_service_net:
    external: true

services:
  django-site:
    build: .
    # with the following line, an alternativ python app could be started
    # command: python3 manage.py blabla
    command: python3 manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    expose:
      - "8001"
    volumes:
      - .:/code
    restart: always
    environment:
      - VIRTUAL_HOST=pv.moik.org
      - VIRTUAL_NETWORK=macs_service_net
      - VIRTUAL_PORT=8001
      - LETSENCRYPT_HOST=pv.moik.org
      - LETSENCRYPT_EMAIL=mike@moik.org
    networks:
      - macs_service_net
