# Generated by Django 2.0 on 2017-12-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SonnenBattery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.SmallIntegerField()),
                ('frequency', models.PositiveSmallIntegerField()),
                ('gridConsumption', models.SmallIntegerField()),
                ('isSystemInstalled', models.BooleanField()),
                ('pacTotal', models.SmallIntegerField()),
                ('production', models.SmallIntegerField()),
                ('rsoc', models.SmallIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ts', models.IntegerField()),
                ('usoc', models.SmallIntegerField()),
                ('uAC', models.PositiveSmallIntegerField()),
                ('uBat', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
