# Generated by Django 2.0 on 2017-12-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonnen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonnenbattery',
            name='ts',
        ),
    ]
