# Generated by Django 2.0 on 2017-12-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonnen', '0002_remove_sonnenbattery_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonnenbattery',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
