# Generated by Django 2.0 on 2017-12-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonnen', '0003_sonnenbattery_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonnenbattery',
            name='hidden',
        ),
    ]
